// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/signup": {
    params: {};
  };
  "/logout": {
    params: {};
  };
  "/api/auth/*": {
    params: {
      "*": string;
    };
  };
  "/api/documents": {
    params: {};
  };
  "/md/:docId?": {
    params: {
      "docId"?: string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/signup" | "/logout" | "/api/auth/*" | "/api/documents" | "/md/:docId?";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/signup.tsx": {
    id: "routes/signup";
    page: "/signup";
  };
  "routes/logout.tsx": {
    id: "routes/logout";
    page: "/logout";
  };
  "routes/api.auth.$.ts": {
    id: "routes/api.auth.$";
    page: "/api/auth/*";
  };
  "routes/api.documents.ts": {
    id: "routes/api.documents";
    page: "/api/documents";
  };
  "routes/md.tsx": {
    id: "routes/md";
    page: "/md/:docId?";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/signup": typeof import("./app/routes/signup.tsx");
  "routes/logout": typeof import("./app/routes/logout.tsx");
  "routes/api.auth.$": typeof import("./app/routes/api.auth.$.ts");
  "routes/api.documents": typeof import("./app/routes/api.documents.ts");
  "routes/md": typeof import("./app/routes/md.tsx");
};